name: Markdown Lint
run-name: MD/Lint

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
            fetch-depth: 0
            persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
      - name: Install Dependencies
        run: npm install -g markdownlint-cli
      - name: Run Markdown Lint
        run: markdownlint ./src/content/blog/*.md
